edit Pkgfile

diff --git a/bluez/bluetoothd b/bluez/bluetoothd
--- a/bluez/bluetoothd
+++ b/bluez/bluetoothd
@@ -1,21 +1,32 @@
 #!/bin/sh
 #
-# /etc/rc.d/bluetoothd: start/stop/restart bluetooth daemon
+# bluetooth startup script
 #
+
+SSD=/sbin/start-stop-daemon
+PROG=/usr/sbin/bluetoothd
+# OPTS="-d"
 
 case $1 in
 start)
-	/usr/libexec/bluetooth/bluetoothd &
+	$SSD --start --exec $PROG -- $OPTS
 	;;
 stop)
-	pkill bluetoothd
+	$SSD --stop --retry 10 --exec $PROG
 	;;
 restart)
-	$0 stop && sleep 2 && $0 start
+	$0 stop
+	$0 start
+	;;
+status)
+	$SSD --status --exec $PROG
+	case $? in
+	0) echo "$PROG is running with pid $(pidof $PROG)" ;;
+	1|3) echo "$PROG is not running" ;;
+	4) echo "Unable to determine the program status" ;;
+	esac
 	;;
 *)
-	echo "usage: $0 [start|stop|restart]"
+	echo "usage: $0 [start|stop|restart|status]"
 	;;
 esac
-
-# End of file
